### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by david-dickinson** [jonbae213/pickup#1]
## MVP List
- [x] looks good!

## Schema
- [x] standardize language between hobbies, communities, categories (here and on the MVP list)
- [x] no need for `things.image` - we’ll use ActiveStorage to attach all files
- [x] `user_things` should be split into two tables - one for `saved_items`, one for `preordered_items`
- [x] `reviews` should link to `preordered_items` table to make sure only ordering users can review and can review once per order

## Sample State
- [x] update to reflect changes to schema
- [x] all entries in entities need unique `id`s
- [x] `users` slice of state needs `hobby_ids`, `thing_ids`
- [x] `things` slice needs `review_ids`
- [x] `reviews` slice needs `thing_id`, `user_id`

## Backend Routes
- [x] user `GET` route needs wildcard `:user_id`
- [x] communities need `GET` index request for the shopping sidebar
- [x] add a basic `GET` request to product index (when there's no community selected, or when we need params like `saved_items` for a user)
- [x] add a `PATCH` route for `reviews` so it has full CRUD

## Frontend Routes
- [x] `/shop` route needs a Sidebar component with community selector

**Comment by jonbae213** [comment]
I should have fixed all the things in the wiki. Please look over one more time and let me know.
